"""
The firmware is developed by 3S JSC.
@ Written by LeKha
"""

WS1812_PIN = 12
BUZZER_PIN = 2
LED_GREEN_POWER = 0
INPUT_BUTTON_POWER = 4
CONTROL_POWER = 15
# SD_CARD_CS = 5
# SD_CARD_SCK = 18
# SD_CARD_MISO = 19
# SD_CARD_MOSI = 23
DRIVE_MOTOR_SDA = 17
DRIVE_MOTOR_SCL = 16
DRIVE_SENSOR_SDA = 21
DRIVE_SENSOR_SCL = 22
DRIVE_SPEAKER = 25
DRIVE_HAL_MOTOR1_CHA = 26
DRIVE_HAL_MOTOR1_CHB = 13
DRIVE_HAL_MOTOR2_CHA = 27
DRIVE_HAL_MOTOR2_CHB = 14
DRIVE_PWMA = 33
DRIVE_PWMB = 32